### ISSUE TITLE
Contact Form does not send emails to ISB

### ISSUE THREAD

**Issue by monicacecilia** [biocuration/isb-website#1]
The form found at http://biocuration.org/contact-the-isb/ is failing to accept and send messages to ISB webmaster.

**Comment by andrewsu** [comment]
The contact page on the ISB website currently just lists the ISB gmail address.  Do we have a need to put the contact form back?  I vote no -- that showing the email address is just fine (and I think better than a contact form).  Objections?

**Comment by monicacecilia** [comment]
I vote "no" with you. I had removed the contact form last month (Jan2017) because it wasn't working. I think it is better to keep just the ISB gmail address.
