### ISSUE TITLE
"Forgot password" feature is not sending email

### ISSUE THREAD

**Issue by andrewsu** [biocuration/isb-website#10]
[Login recovery page](http://biocuration.org/wp-login.php?action=lostpassword) giving this error:

> The email could not be sent.
> Possible reason: your host may have disabled the mail() function.

**Comment by andrewsu** [comment]
Diagnosis: Easy WP SMTP plugin was not sending test messages.  Likely due to some issue with a recent change of gmail requiring OAuth authentication.

Attempt 1: Tried [Gmail SMTP plugin](https://wordpress.org/plugins/gmail-smtp/).  Test emails were being sent fine, but the reset password link was not included in the email because [this issue](https://core.trac.wordpress.org/ticket/21095).  (In short, reset URL was enclosed in "<>", which wasn't being handled correctly.  others suggested that changing mail plugin fixed the issue, so...)

Attempt 2 (worked): Installed [Postman SMTP plugin](https://wordpress.org/plugins/postman-smtp/) following instructions [here](https://www.elegantthemes.com/blog/tips-tricks/use-smtp-to-send-email-from-wordpress).  Confirmed both test emails work and password reset emails work.

NOTE: when we migrate to wpengine, the oauth settings in Postman **_may_** need to be updated.

**Comment by andrewsu** [comment]
error recurred -- somehow Easy WP SMTP got reactivated and Postman SMTP deactivated.  Switched it back and tested.  Seems to work again...

**Comment by monicacecilia** [comment]
It's working now. I can warns on our inbox and successful logins from users requesting resets. 💃
