### ISSUE TITLE
Membership renewal notices not being sent

### ISSUE THREAD

**Issue by andrewsu** [biocuration/isb-website#11]
For those whose memberships are expiring, renewals are not currently being sent.  This issue *may* be fixed by the outgoing email fixes in #10.  Moni is testing/confirming...

**Comment by monicacecilia** [comment]
Tested 'expiring' and 'expired' membership messages. Renewal notices are still failing.

**Comment by andrewsu** [comment]
@monicacecilia can you test again?  Wondering if it got fixed with our SMTP updates associated with #10.  Can you also document how you test renewal notices in this ticket?

**Comment by monicacecilia** [comment]
Tests have been successfully sent and received. 

To testing email templates, including the renewal notices, navigate to: 
1. Dashboard
2. Memberships
3. Email Templates
4. Choose 'Membership Expiring' or 'Membership Expired' from dropdown menu, then click on 'Save Template and Send Email.'

However, Cecilia mentioned she did not get a renewal notice - could be either the scheduling or a spam filter.

**Comment by andrewsu** [comment]
From Sylvain:

> ---------- Forwarded message ----------
> From: Sylvain Poux <Sylvain.Poux@sib.swiss>
> Date: Tue, Aug 15, 2017 at 7:31 AM
> Subject: {Disarmed} Re: {Disarmed} Re: ISB-EC Meeting August 15th
> To: Monica Munoz-Torres <mcmunozt@lbl.gov>, Cecilia Neomi Arighi <arighi@dbi.udel.edu>
> Cc: ISB Exec <intsocbio_ec@googlegroups.com>, Andrew Su <asu@scripps.edu>
> 
> Hi,
> 
> I confirm there is apparently a problem with renewal procedure. Lydie just told me that we have not received any reminder/invoice for the renewal

**Comment by carighi** [comment]
Ceci: 1++

**Comment by monicacecilia** [comment]
++ from @selewis

**Comment by rousnay** [comment]
![image](https://user-images.githubusercontent.com/456973/30785275-92307354-a186-11e7-9a67-b0df91ffe229.png)


@andrewsu , It is sending test email. can i create a demo member with a very short expiration date? so that I can test whether it is working for scheduled email or not.

**Comment by andrewsu** [comment]
Yes, no problem. Please clearly indicate that it is a test user. Thanks!

**Comment by rousnay** [comment]
@andrewsu , After creating a test member with very short expiration date (27th sep) I didn't receive any email yet. 
I have a question, is this notification email option is default by this membership plugin? or it is an optional functionality added using add-on (Extra Expiration Warning Emails Add On)?

If this is the add-on (https://www.paidmembershipspro.com/add-ons/extra-expiration-warning-emails-add-on/) then we should increase the expiration date of the test member to minimum 8 days since this add-on send notification 7 days prior to their expiration date. 

can you confirm please?

**Comment by andrewsu** [comment]
Unfortunately, I don't have the answer for you. We don't have access to
person who set that up. Can you investigate please? Also, it may be that
this is a paid feature -- if that's the case, then let me know and we will
sign up for a paid subscription.

**Comment by rousnay** [comment]
@andrewsu , No worries :)
let me investigate, I have set the expiration date to 6th October, so it should sent notification within 29th September (7 days prior to their expiration date). after 30th September I will take farther steps.

**Comment by rousnay** [comment]
@andrewsu , after waiting of 8 days I didn't get the notifications yet. I will take farther steps tonight.

**Comment by rousnay** [comment]
![image](https://user-images.githubusercontent.com/456973/31271833-b1de801a-aaaa-11e7-8baf-b5939453bb47.png)


![image](https://user-images.githubusercontent.com/456973/31271708-3e03b93a-aaaa-11e7-9621-cb1a7daee25d.png)

![image](https://user-images.githubusercontent.com/456973/31271982-21c1efca-aaab-11e7-9ec6-15a1c3529d80.png)

![image](https://user-images.githubusercontent.com/456973/31271911-e35ed5c2-aaaa-11e7-9aa7-0a8ed9a0fb07.png)

**Comment by andrewsu** [comment]
Apparently reminder/warning emails went out this morning to many people who
should not have received one. I will follow up with more details. I should
have thought of this earlier, but we need to do any further debugging of
this plugin on staging with the user database trimmed to a bunch of test
users...

**Comment by rousnay** [comment]
Oh, sorry for this inconvenience, we should have export/backup the staging database and then removed all the users except demo one.

can i process this?

**Comment by andrewsu** [comment]
If you are doing further testing, then yes please.

**Comment by rousnay** [comment]
@andrewsu , just for notice, please remember that 

> NEVER COPY THE STAGING VERSION TO PRODUCTION VERSION USING WPENGINE ADMIN PANEL

we will always update the production version from our local machine via git push.

**Comment by andrewsu** [comment]
Thank you, noted!

**Comment by rousnay** [comment]
@andrewsu ,

The problem has been fixed!

I have got the warning notification last two consecutive days as expected. 

![image](https://user-images.githubusercontent.com/456973/31319091-294cc19a-ac7f-11e7-87de-2244d24f0fd3.png)

![image](https://user-images.githubusercontent.com/456973/31319096-3a619276-ac7f-11e7-9614-8b05f9f6321b.png)


now let me know the day interval to send warning notification, so that i can set right way. currently it is set to 1,2,3..... 10, 30, 60, and 90 day.

**Comment by andrewsu** [comment]
Please set notification to 60, 30, 7, 3, and 1 days.  Please also note the commit ID in a comment so we can easily see how to adjust these.  (I'm assuming it will be an update in a configuration file.)

**Comment by rousnay** [comment]
@andrewsu , Done!
commit: https://github.com/biocuration/isb-website/commit/a6c85ffedd339521059d11b1a847b3b4a3d7810a

**Comment by monicacecilia** [comment]
Hi @rousnay & @andrewsu. I'd like to thank you both for all the efforts in updating and fixing this issue.

Unfortunately, it appears that we are now sending daily renewal notices, and repeatedly to at least some of our members. One of my coworkers send me a message to let me know that she had received 'yet another reminder to renew'. I checked and indeed there was a group of messages yesterday morning and again this morning. I saw that my coworker received a message at 11:04 AM yesterday and again today at 7:22 AM. Her membership will not expire for another five days.

Could I please hear an update with details of the scheduling that is being followed? Or whether these are being sent out by error? And if the latter is true, what are we doing to overcome the issue?

**Comment by andrewsu** [comment]
@monicacecilia I _think_ 🤞 that everything is working correctly here.  First, all the emails were initiated from our production server, not our staging server, so the links go to the right place.  Second, I spot checked the expiration dates stated in the emails and all of them were correct.  Third, all of the emails are within 60 days of expiration (which is the first notification).  So let's watch this for a couple more days and reassess.

For reference, the current frequency of reminders was set in https://github.com/biocuration/isb-website/issues/11#issuecomment-335060610 and https://github.com/biocuration/isb-website/commit/a6c85ffedd339521059d11b1a847b3b4a3d7810a.

**Comment by monicacecilia** [comment]
@andrewsu - please see what I just found out:

The user I was looking at has a membership expiring on 17 October. According to the schedule, correctly scheduled reminders should go out on October 10, 14, and 16. 
Instead, user received consecutive reminders on October 11 and 12 - this is *after* the emails you sent out with our apologies on October 10th (user had also gotten one that day). 

Of note, there are other seven users, also with an expiring date of 17 October, who also received messages on October 10, 11, and 12. 

I don't think it is working correctly yet. 😞

**Comment by andrewsu** [comment]
Let's give it one more day.  If they get an email tomorrow, something is clearly wrong.  But the emails that went out this morning _could_ have been the reminder system "catching up" with the older reminder(s) (Oct 10 or before) on production.  If all goes well, the user you are talking to should next receive emails on Oct 14 and 16.  You might prep them so they know what to expect.

The other good sign is that the people with expiration dates beyond Oct 17 did not get a reminder on consecutive days, and it looks like all the other emails that went out yesterday and today were as expected.

I know this is frustrating for users and us, but based on separate conversations I've had with @rousnay I'm 80% confident we're set up correctly and just need to wait for the ship to stabilize a bit...

**Comment by rousnay** [comment]
Sorry for this inconvenience, I do agree with @andrewsu about 

> But the emails that went out this morning could have been the reminder system "catching up" with the older reminder(s) (Oct 10 or before) on production.

Let me explain - how this add-on works (as per plugins official documentation).

> The first few times this code runs, it will send expiration notices to members expiring up to and including each level. For example, if 30, 60, 90 day notices are set up:
> 
> members expiring within 30 days will receive the 30 day notice
> members expiring within 31 to 60 days will receive the 60 day notice
> members expiring within 61 to 90 days will receive the 90 day notice 

In our custom setting it is 1, 3, 7, 30 and 60 days. so after very first implementation of this plugin it will send the notification the the users those who in the **MIDDLE** of the day interval cycles - 1 to 3, 3 to 7, 7 to 30 and 30 to 60 days. long story short the plugin will send warning emails to the **ALL** this user those membership is going to expire _within 1 to 60 days_.


NOTE: My assumption could be wrong, since I did't build the plugin from scratch. if the bug persist, let me know.

**Comment by andrewsu** [comment]
no emails went out this morning, which I think is a good sign...

**Comment by andrewsu** [comment]
Again reviewing the emails from the last few days, it looks like all is working well now.  @monicacecilia would you like to review before I close this issue?

**Comment by monicacecilia** [comment]
Thanks @andrewsu. I have reviewed, and we are not quite ready to close it yet. 
A double-message schedule took place today. Everyone who was scheduled to receive a message today (those with upcoming expiration dates and those with already expired memberships) received two of them instead, 3.5 hours apart in all cases. Something is still not quite right - we should only be sending out one message at a time to each person.

**Comment by andrewsu** [comment]
Just to add a couple more details -- the double emails went out to several people whose membership expired today, as well as one person whose membership expires 7 days from now.  All reminder emails from yesterday and the day before yesterday were single emails.  @rousnay any thoughts on what might be going on?

**Comment by andrewsu** [comment]
not seeing more double emails. will continue watchful waiting...

**Comment by rousnay** [comment]
@andrewsu , sorry, I missed this notification. is the bug persist?

**Comment by andrewsu** [comment]
Between Oct 19 and Oct 28, 20 reminder emails (subscription "will end soon" or "has ended") were sent, and among these, there was one example (on Oct 28) where a double email was sent.  So not a high priority ticket, but let's keep this issue open for a while just as a reminder to periodically check in to make sure it hasn't increased in frequency.

**Comment by nicolevasilevsky** [comment]
@sandraorchard do you know if this is still an issue? Can this be closed?

**Comment by rvita** [comment]
new system in place, this thread is obsolete.
