### ISSUE TITLE
Get wordpress site checked into this repo

### ISSUE THREAD

**Issue by andrewsu** [biocuration/isb-website#13]
Probably should get our wordpress code checked in to this repo first thing after migration to wpengine.  Relevant links:

* https://wpengine.com/git/
* https://cdn2.hubspot.net/hubfs/298401/Documents_for_download/WP-WP-GIT-009.pdf
* https://hs.wpengine.com/recorded-webinar-git-in-motion?submissionGuid=efaead44-fb23-46b6-9905-1cb46921f563

**Comment by Drosophilic** [comment]
Sorry, I'm hoping to get to this next week. I'll provide updates on progress here.

**Comment by andrewsu** [comment]
more relevant info in this presentation

https://stevegrunwell.github.io/wordpress-git/#/

particularly the .gitignore 

https://stevegrunwell.github.io/wordpress-git/#/10

**Comment by andrewsu** [comment]
completed by @rousnay in f659138c80aca2b4171b24e627697f60ca24efb0
