### ISSUE TITLE
Set up SSL certificate to route all traffic via https

### ISSUE THREAD

**Issue by kltm** [biocuration/isb-website#15]
When I arrive at biocuration.org, there is a login section. The site does not switch to https by default, so my password would be sent in the clear; not good considering there is a payable membership component. Examining the document, the action for the POST is also plain http.

If I manually try and change the URL to https, the certificate is apparently only valid for ssl13.ovh.net and www.ssl13.ovh.net. It may be worth looking into letsencrypt.org tools.

**Comment by andrewsu** [comment]
completed by @rousnay in https://github.com/biocuration/isb-website/commit/0fd6543559f4aa514bdb504f42d406eeae125c9a
