### ISSUE TITLE
when logged in, need link to wordpress dashboard

### ISSUE THREAD

**Issue by andrewsu** [biocuration/isb-website#19]
When first logging in, users are redirected to the wordpress dashboard.  From there, one can get back to the site using the "visit site" link in the upper-left.  From that state, there does not appear to be a way to get back to the wordpress dashboard.

**Comment by carighi** [comment]
Ceci: 1+

**Comment by andrewsu** [comment]
This issue only applies to editors/administrators, who can use the link in the top header.  Closing issue...
