### ISSUE TITLE
Aggregate a list of articles published by ISB members

### ISSUE THREAD

**Issue by monicacecilia** [biocuration/isb-website#2]
Digital Scholarship releases the [Research Data Curation Bibliography](http://digital-scholarship.org/rdcb/rdcb.htm). There are very few biocuration articles listed here. We should provide a way for ISB members to add their publications to a growing list that can be added to this resource.

**Comment by sandraorchard** [comment]
How do we make it clear this is limited to only their articles on the process of biocuration as the main subject, and not just a list of the NAR publications on their resource (assuming this is what you intend). I can see people copying their entire back catalogue in, if we are not careful.

**Comment by carighi** [comment]
Ceci: 0.

**Comment by nicolevasilevsky** [comment]
@sandraorchard Is this something we want to consider doing? Should I add it to a future agenda?

**Comment by rvita** [comment]
This is beyond the scope of what can be done, will be thousands of publications. Instead we are adding a list of collaborating curated resources to the ISB website.
