### ISSUE TITLE
Add google analytics and grant access to ISB Exec

### ISSUE THREAD

**Issue by Drosophilic** [biocuration/isb-website#21]

**Comment by carighi** [comment]
Ceci: 1+. This is important, but I would first solve the usability issues.

**Comment by monicacecilia** [comment]
+1 from @selewis

**Comment by rousnay** [comment]
@andrewsu , I don't understand the phrase "grant access to ISB Exec ", and should I add the google analytics to my google developer tools account? and then I can transfer the ownership to you.
or you can give me access relevant google account to add analytics.

**Comment by andrewsu** [comment]
@rousnay Is all you need a tracking id?  I just created one here: UA-107767284-1.  Don't worry about the "ISB Exec" part...

**Comment by rousnay** [comment]
@andrewsu ,
Please check the google analytics whether it is working or not.

File: https://github.com/biocuration/isb-website/blob/master/wp-content/themes/twentyfourteen-isb/header.php

commit: https://github.com/biocuration/isb-website/commit/2c9460d7518e5f70769188d3c99b95c77fadb052

**Comment by andrewsu** [comment]
No data is being recorded so far.  I granted you access to the google analytics report...

**Comment by rousnay** [comment]
@andrewsu , It seems the analytics is working as expected, remember that the analytics code is currently placed only in STAGING version, not in PRODUCTION version.

![image](https://user-images.githubusercontent.com/456973/31390965-14de15aa-adf7-11e7-8efa-af8e5fd27c68.png)

**Comment by andrewsu** [comment]
super, looks great!  (I will close these tickets once we push to production and verify all is working there...)

**Comment by rousnay** [comment]
okay
