### ISSUE TITLE
Login screen update - ask for email rather than username

### ISSUE THREAD

**Issue by Drosophilic** [biocuration/isb-website#24]
From https://groups.google.com/forum/#!msg/intsocbio_ec/nRAc0Mas3_A/XKYJmv93DgAJ

**Comment by carighi** [comment]
Ceci 1++

**Comment by monicacecilia** [comment]
++ from @selewis

**Comment by rousnay** [comment]
@andrewsu , I can't see the details in google group since i am not he member of this group. can you add me please or explain this issue in details?
I think it says the login form should only ask for email address, not username (currently it works either way).

**Comment by andrewsu** [comment]
please make this very minor change from "Username" to "Username or email":

![2017-10-08_20-13-10](https://user-images.githubusercontent.com/2635409/31324211-4484119e-ac65-11e7-97f4-3dd47ac9d419.png)

**Comment by rousnay** [comment]
@andrewsu , Done!

**Comment by andrewsu** [comment]
I don't see this change on https://biocuration.staging.wpengine.com/. can you confirm?

**Comment by rousnay** [comment]
@andrewsu , sorry widget was get back to old setting since i imported old database after changing the widget settings, not it has fixed.

widget area:
![image](https://user-images.githubusercontent.com/456973/31401018-555013c4-ae13-11e7-8ede-bdff25bab651.png)
