### ISSUE TITLE
Add a link to the login recovery page

### ISSUE THREAD

**Issue by Drosophilic** [biocuration/isb-website#25]
Add a link to the login recovery page:
https://biocuration.org/wp-login.php?action=lostpassword

~~from the login page:
https://biocuration.org/wp-login.php~~

**EDIT 2017-10-08**: from the front-page login widget: e.g., 

![2017-10-08_20-05-46](https://user-images.githubusercontent.com/2635409/31324131-4b785ede-ac64-11e7-9da6-fc3a563fba0c.png)

**Comment by carighi** [comment]
Ceci 1++

**Comment by monicacecilia** [comment]
+1 from @selewis

**Comment by rousnay** [comment]
@andrewsu ,
can you please explain with more words? because it seems the page already has login recovery link;
![image](https://user-images.githubusercontent.com/456973/31319202-c82b828c-ac80-11e7-8789-ef132fbb6d9a.png)

**Comment by andrewsu** [comment]
@rousnay you're right.  That link does appear on the login page.  I was going to close the issue, but instead have changed it to add a "Forgot password" link to the home page.  Please see the first comment in this issue, which I've just updated...

**Comment by rousnay** [comment]
@andrewsu , Done!

**Comment by rousnay** [comment]
@andrewsu ,
file: isb-website/wp-content/themes/twentyfourteen-isb/footer.php
commit: https://github.com/biocuration/isb-website/commit/fff384c009627dfb31e276a5223d2d26b912b0fe

**Comment by andrewsu** [comment]
another relevant commit: https://github.com/biocuration/isb-website/commit/9fa5adcc5e2c279c32a675df138a788c98098fdc?diff=unified
