### ISSUE TITLE
forgot password link not showing up

### ISSUE THREAD

**Issue by andrewsu** [biocuration/isb-website#27]
If user enters the wrong password, a link to reset the password should show up.  This is what's shown on staging (https://biocuration.staging.wpengine.com)
<img width="340" alt="staging" src="https://user-images.githubusercontent.com/2635409/29881625-f8c6750e-8d5f-11e7-890c-3d0f4bcde1ee.png">

But the link is absent from production:
<img width="316" alt="prod" src="https://user-images.githubusercontent.com/2635409/29881537-bb00f2bc-8d5f-11e7-8e7e-305425793a61.png">

The link should go to https://www.biocuration.org/wp-login.php?action=lostpassword

**Comment by monicacecilia** [comment]
Discussed again on 2019-09-12 EC meeting. 
We have sent URL to users with recently expired / soon to expire memberships (to end of Sept 2017).

**Comment by rousnay** [comment]
@andrewsu @monicacecilia SOLVED!

**Comment by andrewsu** [comment]
great! Can you describe the solution please? This one was very puzzling to me...

**Comment by rousnay** [comment]
@andrewsu  I have checked user.php file in wp-include folder but the file was perfect, then disabled few security plugin but the issue was persist, then I search by "Lost your password" in theme folder and I found that this option was disabled by custom code in theme's function.php file (line 26-31)

**Comment by andrewsu** [comment]
https://github.com/biocuration/isb-website/commit/8ba5993545211507f15f4b3d5d3e0745e34b8a63

very interesting...  I'm still confused as to why that function didn't *also* remove it from the staging site. If you have thoughts on that, please let me know (as it may point to an issue with my deploy procedure).

Also, I noticed three new files in the commit.  Are those also a necessary part of the solution?

**Comment by rousnay** [comment]
I). Three other files ( .htaccess, WPENGINgitignore.txt, recommended-gitignore-no-wp.txt) are ignored by .gitignore (what i had written once) but now I am using updated .gitignore file (written by you) where the text file and .httaccess are not in ignore list. anyway, .htaccess optional but some times they do important job, it is better to keep it in server. and other two files are nothing but some ignore list i have collected from internet few months ago, I am going to remove these files from working directory.

I). I have edited the production version of the site, as you said that staging version is working well. I think we can copy the live version to staging. My git push environment was setup to production version, i think i should change it to staging version.

**Comment by andrewsu** [comment]
Got it.  Yes, I like your suggestion to keep .htaccess and remove the other two. Please make that change.

My confusion on staging was that I had pushed the same code to both of them (I think) and saw different behavior.  Anyway, not a big issue, no need to investigate more...

Thanks! Closing ticket now...

**Comment by rousnay** [comment]
@andrewsu Unwanted files has been removed and my git environment has pointed to staging version, I would suggest you to push the updates in github first and then wpengine staging as we working together. I will pull changes from github first and then push to github then to staging so that you can get my updated codes from github to your local machine.
and finally we can copy the staging version to production version after approval.
It that oky?

**Comment by andrewsu** [comment]
@rousnay sorry, missed replying to this.  I am not actively doing anything regarding code changes at the moment.  (I will let you know if that changes.)  So you can go ahead and push to production and staging whenever you are ready.  When I go to do any further development, I will pull from github directly...
