### ISSUE TITLE
remove odd login logo from the home page

### ISSUE THREAD

**Issue by andrewsu** [biocuration/isb-website#28]
Remove the icon highlighted by the red arrow below:

![2017-10-08_20-05-46](https://user-images.githubusercontent.com/2635409/31324162-b4356110-ac64-11e7-968d-f752a9896c75.png)

**Comment by rousnay** [comment]
@andrewsu , Done!

it was removed from Widget settings since this login form was added via widget are.

**Comment by andrewsu** [comment]
which widget controls this?  Also, the image still shows up after user is logged in -- let's remove this too...

**Comment by rousnay** [comment]
Removed.
widget settings  area:
![image](https://user-images.githubusercontent.com/456973/31401074-7fa17668-ae13-11e7-863c-6585ad873580.png)
