### ISSUE TITLE
documenting behavior of recurring memberships

### ISSUE THREAD

**Issue by andrewsu** [biocuration/isb-website#29]
this issue is to document how PMP's "recurring memberships" work from the end user perspective.

**Comment by andrewsu** [comment]
settings for "test" membership level

<img width="1178" alt="2017-10-23_10-22-46" src="https://user-images.githubusercontent.com/2635409/31903177-392f1942-b7dc-11e7-84d8-489eccd3adb3.png">

**Comment by andrewsu** [comment]
sign up message from website after entering paypal info

<img width="535" alt="2017-10-23_10-21-25" src="https://user-images.githubusercontent.com/2635409/31903202-4dbc6afe-b7dc-11e7-9bcd-4d61ea908813.png">

**Comment by andrewsu** [comment]
welcome email

> ---------- Forwarded message ----------
> From: International Society for Biocuration <intsocbio@gmail.com>
> Date: Mon, Oct 23, 2017 at 10:18 AM
> Subject: Your membership confirmation for International Society for Biocuration
> To: andrew.su@gmail.com
> 
> 
> Thank you for your membership to International Society for Biocuration. Your membership account is now active.
> 
> Below are details about your membership account and a receipt for your initial membership invoice.
> 
> Account: asu_test (andrew.su@gmail.com)
> 
> Membership Level: test
> 
> Membership Fee: The price for membership is CHF 1.00 every 7 Days.
> 
> Invoice #061A5E7145 on October 23, 2017
> Total Billed: CHF 1.00
> 
> Log in to your membership account here: https://biocuration.staging.wpengine.com/wp-login.php?redirect_to=https%3A%2F%2Fbiocuration.staging.wpengine.com%2Fmembership%2Fmembers-zone%2Fmembership-account%2F
> 
>

**Comment by andrewsu** [comment]
welcome email on recurring payment from paypal

<img width="682" alt="2017-10-23_10-29-20" src="https://user-images.githubusercontent.com/2635409/31903509-283851a2-b7dd-11e7-9820-90d26724e78a.png">

**Comment by andrewsu** [comment]
next notice was the charge from paypal -- no warning/altert from either wordpress or paypal.
![2017-10-30_11-25-03](https://user-images.githubusercontent.com/2635409/32188604-7f136272-bd65-11e7-8bb6-ff63b39c6b1f.png)

@rousnay can you check why I did not receive warning emails from staging?  Are they designed not to be sent on recurring payments?  Can we set them up so that warning/notification emails are sent?  Note 
that I set up the "test" level for a seven day billing cycle, but if we put this on our production site it would be for a one year billing cycle.  This period length is just for testing...

**Comment by rousnay** [comment]
@andrewsu , Membership plugin don't offer this option (or disabled intentionally), they rather offer an add-on to use this feature https://www.paidmembershipspro.com/add-ons/recurring-payment-email-reminders/

**Comment by rousnay** [comment]
and also note that, yesterday i have remove some more user from the admin panel, these users are not the admin, subscriber or any privilege, not even have any membership. previously I skipped them by mistake.

**Comment by rousnay** [comment]
@andrewsu , is there any update about this issue? if you are planning to implement this add-on, you can provide me this add-on so that i can go for next step.

**Comment by nicolevasilevsky** [comment]
@sandraorchard can this be closed?
