### ISSUE TITLE
Better citation of ISB databases

### ISSUE THREAD

**Issue by monicacecilia** [biocuration/isb-website#3]
@mellybelly
Recommendations for better citation of ISB databases, including resolvable, persistent URIs for the databases using the Biosharing/biocoreDB identifiers. This is similar to what has been implemented for the OBO Foundry: http://www.obofoundry.org/docs/Citation.html. We want more attribution and better tracking.

**Comment by Drosophilic** [comment]
1. Could we ask members to add their database bioDBcore ID when they fill in their membership form? (if they don't know what it is or their resource doesn't have one, we could point them towards FAIRsharing where they can get one)

2. We could add a page to the community menu outlining these recommendations (i.e. make sure your resource has a bioDBcore ID/is in FAIRsharing.org, mark-up your database with bioschemas, and so on)

**Comment by carighi** [comment]
Ceci: 0.

**Comment by rvita** [comment]
we are adding a collaboration/curated resources page to the ISB website.
