### ISSUE TITLE
Error: Express checkout payer ID missing

### ISSUE THREAD

**Issue by monicacecilia** [biocuration/isb-website#30]
Two users have reported that, upon clicking on the 'Complete Payment' button using PayPal, they get an error that reads "Express checkout payer ID missing."

Both reports were issued via email. 

The first report, from 2-Oct-2017, was solved by updating the user's membership type (it was missing for some reason), and adding an expiration date (also missing) to her member profile. After that, the user was able to process the payment. 

The second report was issued on 7-Nov-2017. Again, the user reported that he was not able to complete the transaction. In this case, there is not an already existent profile for the user. 

My recommendation is to: 
- [ ] create a profile for the user, including name and email address, and generate a password and save it (but do not distribute).
- [ ] ask user to generate a new password (using magic URL from login page), 
- [ ] ask user to try to make a payment for his 'expired' membership using PayPal.

-----------
### Screenshot: 

![screen shot 2017-10-02 at 11 30 20 am](https://user-images.githubusercontent.com/1714621/32542692-a6ebdb68-c430-11e7-9c2b-1f9f575ea790.jpg)

**Comment by carighi** [comment]
I search this error message in Google, and  there seems to be a problem with wordpress and paypal express, here are some links that may help providing an answer to this:
https://www.paypal-community.com/t5/About-Payments-Archive/Express-Checkout-PayerID-is-missing/td-p/905209
http://www.webassist.com/forums/posts.php?id=20525
https://wordpress.org/support/topic/paypal-express-checkout-error-2/

**Comment by andrewsu** [comment]
On further look at this, looks like this is a wpengine issue. Two additional links:

https://wordpress.org/support/topic/10419-express-checkout-payerid-is-missing-2/
https://wpengine.com/support/wpengine-ecommerce/

**Comment by andrewsu** [comment]
More specific guidance from Paid Memberships Pro here: https://www.paidmembershipspro.com/wp-engine/

Asked wpengine support to exclude membership-checkout/*, /membership-account and /wp-admin/admin-ajax.php

All appears to be working now...  (fingers crossed)

**Comment by carighi** [comment]
OK, thank you Andrew for looking further into this!
So from what I understand it should be working now!
We will ask our EC members to try in tomorrow's meeting (with the blessing
from Sandra that she will be able to reimburse)
Best
ceci
