### ISSUE TITLE
Explore adding widget from ELIXIR TeSS focusing on Biocurator training materials and events

### ISSUE THREAD

**Issue by Drosophilic** [biocuration/isb-website#31]
ELIXIR TeSS collates training materials and events (not just in Europe) from Goblet, ELIXIR and more. As I work with TeSS and their developers as part of ELIXIR-UK, I'll explore how we can add a widget to display Biocurator-relevant training and events on the ISB website.

**Comment by Drosophilic** [comment]
Update: Working with Niall Beard (ELIXIR/Goblet/TeSS) on the TeSS code.

**Comment by Drosophilic** [comment]
Code for the widget is available here: https://elixirtess.github.io/list_widget/#
It looks highly customisable and we should be able to filter on 'biocuration'. I'll have a play with adding it to the WordPress site to see if it can work properly.

**Comment by Drosophilic** [comment]
I have placed the widget on the right hand column for now. It is visible there for all users.

As I mentioned before, it is highly customisable. We can have some topics, countries etc. listed as filters available above the table, if we like.

Arguably, the widget may work better on it's own page on WordPress, although Wordpress doesn't allow active code to be inserted into the page/post itself. I'll try and find a workaround to this when I see Niall at the start of June.

**Comment by Drosophilic** [comment]
The widget itself is very slow to load, leading to a 'spinning disc of death'. I'll speak to Niall about that.

**Comment by andrewsu** [comment]
Just a note that when you get it finalized, we'll want to get this added to the code repo, otherwise it'll get overwritten on next update. I can walk you through that...

**Comment by Drosophilic** [comment]
The widget is now pretty much set up. I'd like to add a search box to the top of the widget but otherwise it's ready to go.

Would it be worth exploring setting up a separate page for a larger version of the widget (e.g. with a table display, tags/filter options and other search options? This could take a little time as WordPress doesn't like to have code other than WP code on the page, but I could spend some time to find a workaround if it's considered worthwhile.

**Comment by Drosophilic** [comment]
I've added a search box to the widget.
