### ISSUE TITLE
Move "members' zone" to header

### ISSUE THREAD

**Issue by andrewsu** [biocuration/isb-website#34]
Currently there is a "Members' Zone" link under the "Membership" menu item in the navigation bar.  But, for users who are not logged in, the site directs the user to a blank page, to the membership signup form, or the home page.  Better to display the Member Zone only to users who are logged in.  I suggest something like this: 

![member_header](https://user-images.githubusercontent.com/2635409/36190724-b071f5a2-110e-11e8-8b4e-0a35100b0b09.jpg)

Note that users can still reach the signup page under the "membership" menu item using the "Membership Fees and Payment" link.

**Comment by Drosophilic** [comment]
I'm having difficulty getting the site to let me do this. Let me spend a little more time on this to see if I can figure it out.

**Comment by nicolevasilevsky** [comment]
I think this is fixed, closing
