### ISSUE TITLE
evaluate mailchimp versus google groups

### ISSUE THREAD

**Issue by andrewsu** [biocuration/isb-website#35]
We need to get our mailing list off of OVH.  The question is to what.  Mailchimp and Google groups seem like the obvious answers.  Need someone to evaluate which is best (pro/con list) and devise a migration strategy.  

Criteria (incomplete -- please add)
* cost
* A/B testing
* automatic sync with wordpress member list
* viewing archives
* interacting with each other

Also relates to #5

**Comment by andrewsu** [comment]
migration to google groups in progress https://groups.google.com/forum/#!forum/isb-biocuration

**Comment by andrewsu** [comment]
migration complete

**Comment by nicolevasilevsky** [comment]
Thanks @andrewsu!
