### ISSUE TITLE
Receiving bogus(?) membership information over email

### ISSUE THREAD

**Issue by kltm** [biocuration/isb-website#40]
When I login to biocuration.org, my membership expiration is listed as: March 1, 2019 .
 
However, your staging(?) server seems to believe that it has just expired:

```
From: International Society for Biocuration <XXX@YYY>
To: XXX@YYY
Subject: Your membership at International Society for Biocuration has ended
Date: Tue, 13 Mar 2018 07:43:16 +0000
Content-Transfer-Encoding: quoted-printable
Content-Disposition: inline
MIME-Version: 1.0

<p>Your membership at International Society for Biocuration has ended.</=
p>=0A=0A<p>Thank you for your support.</p>=0A=0A<p>View our current memb=
ership offerings here: https://biocuration.staging.wpengine.com/membersh=
ip/membership-levels/</p>=0A=0A<p>Log in to manage your account here: ht=
tps://biocuration.staging.wpengine.com/wp-login.php</p>
```

**Comment by andrewsu** [comment]
thank you @kltm for reporting this bug.

I tracked down the issue in our build/deploy process and fixed it in b1ee48d5735898e98c0f3d08ca1e906bccf6da56. Now checking to see if anyone actually renewed through the staging site.  Will also need to send out mea culpa emails to everyone who received these erroneous expiration reminders...

**Comment by kltm** [comment]
NP and thank you. Just so you know, I first got this at "12:43 AM" and have just gotten another one now at "05:25 PM" (assuming deployment caused it to trigger again?).

**Comment by andrewsu** [comment]
all mea culpa emails sent. One user who payed a duplicate renewal via the staging site has been contacted for refund.  @sandraorchard, can you close this ticket when the refund has been processed?

**Comment by sandraorchard** [comment]
Done
