### ISSUE TITLE
Exchange Fellowship

### ISSUE THREAD

**Issue by sandraorchard** [biocuration/isb-website#41]
Add page travel Fellowships, child of Community.
Add text to page https://docs.google.com/document/d/1BkMT0iRZdbstHRSGzyer0HVaqAZHp6_UjTYZxC1Yi9s/edit#heading=h.co2diagh924g
Link from membership>Why join the Society
 Leadership, Recognition, Awards, Funding

    Opportunities to lead and influence the field with your vision.
    ISB Awards – Career, Exceptional Contributions.
    Travel Fellowships.
    **Exchange Fellowships**.

**Comment by nicolevasilevsky** [comment]
done
