### ISSUE TITLE
add examples of microgrant funding to website

### ISSUE THREAD

**Issue by nicolevasilevsky** [biocuration/isb-website#42]
Add to website: in the past, microgrants have been used to fund poster session room rentals, offering assistance for travel

All: Please add more examples if you know of any

**Comment by sandraorchard** [comment]
Speaker costs (though I suspect that was a euphemism for travel costs for participants).
Other costs meetings incur:
Attendee accommodation
Admin costs
Bus hire, accommodation to venue

**Comment by Drosophilic** [comment]
Website updated - https://www.biocuration.org/community/microgrants/
