### ISSUE TITLE
link to 1st Biocuration Conference Group Picture is missing

### ISSUE THREAD

**Issue by nicolevasilevsky** [biocuration/isb-website#43]
on this page https://www.biocuration.org/community/conferences/international-biocuration-meetings/

the link to the '1st Biocuration Conference Group Picture' is missing. We should remove this link if we no longer have the picture.

**Comment by nicolevasilevsky** [comment]
also the link to info about the 1st conference is missing too

**Comment by Drosophilic** [comment]
All broken links have now been removed. I'm going to check if I can find any via the wayback machine. 
To avoid this in the future, we could add https://wordpress.org/plugins/broken-link-checker/

**Comment by Drosophilic** [comment]
I've added the conference photo from 2005 back on the page.
