### ISSUE TITLE
13th conference call

### ISSUE THREAD

**Issue by sandraorchard** [biocuration/isb-website#45]
Please update http://biocuration.org/call-host-the-12th-international-biocuration-conference/

to be the 13th conference, text as in email (below).

Dear Colleagues,

 The Executive Committee of the International Society for Biocuration would like to once again invite tenders to host the 13th International Biocuration Conference during the Northern Spring or Summer of 2020.

 Individuals and organizations interested in applying may do so by sending a proposal to the ISB Executive Committee (intsocbio@gmail.com) on or before August 31, 2018.

 The successful bidder will be notified by October 1, 2018. The ISB Executive Committee will publicly announce the selected organization or individuals during the 12th International Biocuration Conference, to be held in Cambridge, UK in April, 2019.

 Format:  

Proposals should be short; length should not exceed one side of an A4 or US letter size sheet, using 11 point font.

 The proposal should contain:

    The name and institution of the local organizer

    Details of the proposed venue for up to 350 participants

    The range of dates available for the conference

    A brief outline of a strategic plan to attract a broad range of participants from the Biocuration community

    As fair gender representation is positively encouraged by the ISB; we would also like to know how the applicant intends to promote this.

In a continued effort to bring our meeting to curators in all geographic regions, we strongly encourage ISB members to put forward proposals to bring the ISB meeting to your region once again, or for the first time! Based on ISB meeting region rotation, for ISB 2019 we are encouraging an American location, but will also consider other locations.

 REGIONS ROTATION:

Asia and Australasia

Europe

Americas

This Call for Applications is also available on the ISB website at http://biocuration.org/call-host-the-12th-international-biocuration-conference/

 For more information about the ISB and our previous conferences, please visit: http://www.biocuration.org

 We look forward to hearing from you!

 Your colleagues at the ISB Executive Committee.

**Comment by Drosophilic** [comment]
Done. See - https://www.biocuration.org/call-host-the-13th-international-biocuration-conference/
