### ISSUE TITLE
Membership fees

### ISSUE THREAD

**Issue by carighi** [biocuration/isb-website#46]
Add 3 new rows:
1-Biocurator, Developer, Bioinformatician (Developing country)
2-Principal Investigator (Developing country)
3-Student (Developing country)

Apply rates based on discussion of existing structure in other places. 
Provide link to list of Developing countries

**Comment by nicolevasilevsky** [comment]
reminder that this is still outstanding

**Comment by sandraorchard** [comment]
Suggest
1. 40 CHF
2. 30 CHF
3. 15 CHF

**Comment by carighi** [comment]
Pete,
 Where are we with this?
If this is finalized we can send to contacts (like the biocuration community in India), the expired members, etc

**Comment by Drosophilic** [comment]
Hi all, this is still outstanding.  I'm afraid I've been rushed off my feet this last month with various crises and unexpected situations.

**Comment by nicolevasilevsky** [comment]
@Drosophilic do you know how to edit the table? Could you (or someone else) show me how to do it?

**Comment by sandraorchard** [comment]
Also on https://www.biocuration.org/membership/membership-levels/ can we add a general statement "If you do not wish to pay be PayPal, contact us on (whatever the membership email is) to discuss alternative options"

**Comment by nicolevasilevsky** [comment]
this has been addressed and can be closed.

For future reference, go to this page to update membership pricing:
https://www.biocuration.org/wp-admin/admin.php?page=pmpro-membershiplevels
