### ISSUE TITLE
add job posting

### ISSUE THREAD

**Issue by nicolevasilevsky** [biocuration/isb-website#49]
Dear ISB Members,

We are looking to hire two Bioinformatics/Scientific Curators at our Thermo Fisher Scientific, Ann Arbor, MI site.

Description
The Bioinformatics Scientist III (Scientific Curator) will review, analyze and compile clinical data from primary literature and clinical trials specific to biomarkers in cancer. They will provide scientific and technical expertise to a cross-functional team of scientists and software developers to build and maintain an internal knowledge base of genomic aberrations and relevant therapies related to cancer.

What will you do?
• Curate evidence from approved drug labels, clinical guidelines and clinical trials using customized software tools.
• Leveraging the primary literature, write narratives describing the relationships between gene variants and disease prognosis, diagnosis, and therapy selection.
• Provide translational oncology expertise to curation team.
• Work in a fast pace, cross-functional team of bioinformatics scientists, data scientists, and software engineers.

Apply: http://jobs.brassring.com/tgwebhost/SM.aspx?cid=25196&phid=61836&rcid=

Please feel free to pass this information to anyone who might be interested.

Thank you

Regards

Dinesh Cyanam
Bioinformatics Scientist III
Clinical Next Gen Sequencing
Life Sciences Solutions
 
Thermo Fisher Scientific 
110 Miller Avenue, Floor 2 | Ann Arbor, MI  48104
Phone: +1 (734) 913-1942 | Mobile: +1 (732) 666-3843
dinesh.cyanam@thermofisher.com | thermofisher.com

**Comment by Drosophilic** [comment]
This appears to already be up on https://www.biocuration.org/community/jobs/
