### ISSUE TITLE
Update mailing list name

### ISSUE THREAD

**Issue by monicacecilia** [biocuration/isb-website#5]
Update mailing list name from _[mailinglist]_ to _[biocuration]_.

**Comment by andrewsu** [comment]
OVH apparently does not allow renaming of maililng lists.  We can try emailing OVH support -- perhaps they can do that via another method.

eventually I think we should just convert the mailing list to a google group or mailchimp.

**Comment by andrewsu** [comment]
moving off of OVH, so moot point...
