### ISSUE TITLE
Formatting is off on the EC members page

### ISSUE THREAD

**Issue by nicolevasilevsky** [biocuration/isb-website#55]
The formatting is off on this page: https://www.biocuration.org/about/executive-commitee/

I can't figure out how to fix it. Looks like Wordpress changed the template. The table below the current EC members doesn't look great either.

@andrewsu or @Drosophilic could you take a look? Thank you!

**Comment by andrewsu** [comment]
I tried adding a new table with the visual "blocks" editor, but that had two problems -- first, there are still alignment issues (though different than the one that currently exists), and second the image HTML code would need to be pasted in by hand into each cell.  I'm thinking there's no way around #2 unfortunately.  So the best solution I can see here is to copy the HTML code for the table of previous EC members, and then copy-paste in the correct information.  PITA...  Will try to have a crack at this, but a bit swamped at the moment...

**Comment by nicolevasilevsky** [comment]
Oh! I think I figured out a way I can fix it, by adding these **media & text blocks**. I'll fix this - thank you for looking into this @andrewsu!

![image](https://user-images.githubusercontent.com/6722114/56537976-b57c0300-6516-11e9-8a4d-a779a7170a97.png)
