### ISSUE TITLE
Not in membership list

### ISSUE THREAD

**Issue by pfey03** [biocuration/isb-website#69]
H I paid membership on September 21, 2020 but I'm not listed in the membership list. I have the confirmation email that I have paid from that date. I do get biocuration emails. What should I do to be listed?
Thanks
Petra

**Comment by nicolevasilevsky** [comment]
@pfey03 sorry about this, I'll address it now

**Comment by nicolevasilevsky** [comment]
I see you are a member, and your membership is valid through Mar 21, 2022.

What list are you referring to?

**Comment by pfey03** [comment]
Hmm funky. I went through list and searched for my full name, part name and it didn't come up. And now it came up. strange really as I tried really to find my status and only when I could not find searched my email. 
Ok thanks NicolesI close the issue
