### ISSUE TITLE
Brainstorming website improvements

### ISSUE THREAD

**Issue by andrewsu** [biocuration/isb-website#7]
let's keep this issue open as a forum to brainstorm website improvements.

**Comment by andrewsu** [comment]
- Move login form in left nav to prominent "Join or renew membership" button in right header ([seconded](https://groups.google.com/d/msg/intsocbio_ec/nRAc0Mas3_A/8LLeOCh4DgAJ))
- re-skin http://biocuration.org/wp-login.php to be like rest of site
- enable multi-year membership
- [change login screen to ask for email instead of username](https://groups.google.com/d/msg/intsocbio_ec/nRAc0Mas3_A/XKYJmv93DgAJ)
- [simplify renewal process](https://groups.google.com/d/msg/intsocbio_ec/3hneMMlgAJc/MMktJtl3DgAJ)

**Comment by andrewsu** [comment]
add google analytics

**Comment by carighi** [comment]
This one is ongoing

**Comment by rvita** [comment]
google analytics was added, new website design underway. these suggestions have been taken into consideration.
